name: YaQuest
main: com.rabbitown.yaquest.YaQuest
version: ${version}
api-version: 1.13
author: Yoooooory
description: Maybe an easy plugin to create a quest.
website: https://github.com/Yallage/YaQuest

depend: [YaLib]
softdepend: [PlaceholderAPI]

permissions:
  yaquest.admin:
    description: YaQuest admin permission.
    children:
      yaquest.admin.reload: true
    default: op